backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "writing-desk"
    label: "Writing Desk Blog"
    folder: "src/pages/writing-desk"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: image,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - label: "Colors"
    name: "colors"
    files:
      - label: "Color Configuration"
        name: "color-config"
        file: "src/config/colors.json"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "color",
            }
          - { label: Blue, name: blue, widget: string }
          - { label: Dark Blue, name: darkBlue, widget: string }
          - { label: Lighter Blue, name: lighterBlue, widget: string }
          - { label: Lightest Blue, name: lightestBlue, widget: string }
          - { label: Gray, name: gray, widget: string }
          - { label: Link Colors, name: linkColors, widget: string }
          - { label: Nav Link Text, name: navLinkText, widget: string }
          - { label: Featured Post, name: featuredPost, widget: string }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Banner Title, name: bannerTitle, widget: string }
          - { label: Banner Subtitle, name: bannerSubtitle, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }

          - { label: "Form Headline", name: "formHeadline", widet: "string" }
          - {
              label: "Form Subheadline",
              name: "formSubHeadline",
              widet: "string",
            }
          - { label: "Form Paragraph", name: "formParagraph", widet: "string" }

          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: ImageAlt, name: imageAlt, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Banner Image", name: "bannerImage", widget: "image" }
          - {
              label: "Banner Image Headline",
              name: "bannerImageHeadline",
              widget: "string",
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }

      - file: "src/pages/the-grove/index.md"
        label: "The Grove"
        name: "the-grove"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "the-grove",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Banner Image", name: "bannerImage", widget: "image" }
          - {
              label: "Banner Image Headline",
              name: "bannerImageHeadline",
              widget: "string",
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "Form Headline", name: "formHeadline", widet: "string" }
          - {
              label: "Form Subheadline",
              name: "formSubHeadline",
              widet: "string",
            }
          - { label: "Form Paragraph", name: "formParagraph", widet: "string" }

      - file: "src/pages/writing-desk/index.md"
        label: "The Writing Desk"
        name: "the-writing-desk"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "the-writing-desk",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Banner Image", name: "bannerImage", widget: "image" }
          - {
              label: "Banner Image Headline",
              name: "bannerImageHeadline",
              widget: "string",
            }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/the-mat/index.md"
        label: "The Mat"
        name: "the-mat"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "the-mat",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Banner Image", name: "bannerImage", widget: "image" }
          - {
              label: "Banner Image Headline",
              name: "bannerImageHeadline",
              widget: "string",
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
